Config = {}

Config.Healing = 3 -- // If this is 0, then its disabled.. Default: 3.. That means, if a person lies in a bed, then he will get 1 health every 3 seconds.
Config.Cooldown = 2 -- // If this is 0, then its disabled.. Default: 2.. That means, if a player goes and stand up, then he need to wait 2 seconds, before he can lay/sit again! [VERY RECOMMENDED]

Config.objects = {
	Object = nil, ObjectVertX = nil, ObjectVertY = nil, ObjectVertZ = nil, ObjectDir = nil, isBed = nil, -- // Please don't change this line!;)
	ButtonToSitOnChair = 23, -- // Default: G -- // https://docs.fivem.net/game-references/controls/
	ButtonToLayOnBed = 23, -- // Default: E -- // https://docs.fivem.net/game-references/controls/
	ButtonToStandUp = 38, -- // Default: F -- // https://docs.fivem.net/game-references/controls/
	SitAnimation = {anim='PROP_HUMAN_SEAT_CHAIR_MP_PLAYER'},
	BedBackAnimation = {dict='anim@gangops@morgue@table@', anim='ko_front'},
	BedStomachAnimation = {anim='WORLD_HUMAN_SUNBATHE'},
	BedSitAnimation = {anim='WORLD_HUMAN_PICNIC'},
	locations = {
		[1] = {object="v_med_bed2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true, coords=false},
		[2] = {object="v_serv_ct_chair02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=168.0, bed=false, coords=false},
		[3] = {object="prop_off_chair_04", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false, coords=false},
		[4] = {object="prop_off_chair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false, coords=false},
		[5] = {object="prop_off_chair_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false, coords=false},
		[6] = {object="v_club_officechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false, coords=false},
		[7] = {object="v_ilev_leath_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false, coords=false},
		[8] = {object="v_corp_offchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false, coords=false},
		[9] = {object="v_med_emptybed", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true, coords=false},
		[10] = {object="Prop_Off_Chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[11] = {object="prop_bench_01a", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[12] = {object="prop_bench_01b", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[13] = {object="prop_bench_01c", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[14] = {object="prop_bench_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[15] = {object="prop_bench_03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[16] = {object="prop_bench_04", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[17] = {object="prop_bench_05", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[18] = {object="prop_bench_06", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[19] = {object="prop_bench_08", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[20] = {object="prop_bench_09", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[21] = {object="prop_bench_10", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[22] = {object="prop_bench_11", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[23] = {object="prop_fib_3b_bench", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[24] = {object="prop_ld_bench01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[25] = {object="prop_wait_bench_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[26] = {object="hei_prop_heist_off_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[27] = {object="hei_prop_hei_skid_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[28] = {object="prop_chair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[29] = {object="prop_chair_01b", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[30] = {object="prop_chair_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[31] = {object="prop_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[32] = {object="prop_chair_04a", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[33] = {object="prop_chair_04b", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[34] = {object="prop_chair_05", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[35] = {object="prop_chair_06", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[36] = {object="prop_chair_08", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[37] = {object="prop_chair_09", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[38] = {object="prop_chair_10", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[39] = {object="prop_chateau_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[40] = {object="prop_clown_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[41] = {object="prop_cs_office_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[42] = {object="prop_direct_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[43] = {object="prop_direct_chair_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[44] = {object="prop_gc_chair02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[45] = {object="prop_off_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[46] = {object="prop_off_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[47] = {object="prop_off_chair_04", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[48] = {object="prop_off_chair_04b", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[49] = {object="prop_off_chair_04_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[50] = {object="prop_off_chair_05", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[51] = {object="prop_old_deck_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[52] = {object="prop_old_wood_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[53] = {object="prop_rock_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[54] = {object="prop_skid_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[55] = {object="prop_skid_chair_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[56] = {object="prop_skid_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[57] = {object="prop_sol_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[58] = {object="v_med_bed", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true, coords=false},
		[59] = {object="v_med_fabricchair1", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		[60] = {object="p_armchair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[61] = {object="p_clb_officechair_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[62] = {object="p_dinechair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[63] = {object="p_ilev_p_easychair_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[64] = {object="p_soloffchair_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[65] = {object="p_yacht_chair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[66] = {object="v_club_officechair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[67] = {object="v_corp_bk_chair3", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[68] = {object="v_corp_cd_chair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[69] = {object="v_corp_offchair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[70] = {object="v_ilev_chair02_ped", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[71] = {object="v_ilev_p_easychair", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[72] = {object="v_ret_gc_chair03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[73] = {object="prop_ld_farm_chair01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[74] = {object="prop_table_04_chr", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[75] = {object="prop_table_05_chr", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[76] = {object="prop_table_06_chr", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[77] = {object="v_ilev_leath_chr", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[78] = {object="prop_table_01_chr_a", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[79] = {object="prop_table_01_chr_b", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=0.0, direction=270.0, bed=false, coords=false},
		[80] = {object="prop_table_02_chr", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[81] = {object="prop_table_03b_chr", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[82] = {object="prop_table_03_chr", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[83] = {object="prop_torture_ch_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[84] = {object="v_ilev_fh_dineeamesa", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[85] = {object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[86] = {object="v_ilev_tort_stool", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[87] = {object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[88] = {object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[89] = {object="hei_prop_yah_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[90] = {object="hei_prop_yah_seat_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[91] = {object="hei_prop_yah_seat_03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[92] = {object="prop_waiting_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[93] = {object="prop_yacht_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[94] = {object="prop_yacht_seat_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[95] = {object="prop_yacht_seat_03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[96] = {object="prop_hobo_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[97] = {object="prop_rub_couch01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[98] = {object="miss_rub_couch_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[99] = {object="prop_ld_farm_couch01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[100] = {object="prop_ld_farm_couch02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[101] = {object="prop_rub_couch03", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[102] = {object="prop_rub_couch04", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[103] = {object="p_lev_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[104] = {object="p_res_sofa_l_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[105] = {object="p_v_med_p_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[106] = {object="p_yacht_sofa_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[107] = {object="v_ilev_m_sofa", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[108] = {object="v_res_tre_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[109] = {object="v_tre_sofa_mess_a_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[110] = {object="v_tre_sofa_mess_b_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[111] = {object="v_tre_sofa_mess_c_s", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[112] = {object="prop_roller_car_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[113] = {object="prop_roller_car_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[114] = {object="v_ilev_ph_bench", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[115] = {object="ex_prop_offchair_exec_04", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[116] = {object="ex_prop_offchair_exec_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[117] = {object="vw_prop_vw_offchair_02", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[118] = {object="vw_prop_casino_chair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		[119] = {object="vw_prop_casino_track_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, coords=false},
		--jail bed
		[120] = {position = vector3(1768.3,2587.18,45.27), verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true, coords=true},
		--jail 1f sit face gym
		[121] = {position = vector3(1780.35,2581.52,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		[122] = {position = vector3(1776.49,2577.65,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		[123] = {position = vector3(1776.48,2581.69,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		[124] = {position = vector3(1776.38,2585.19,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		[125] = {position = vector3(1780.26,2585.25,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		[126] = {position = vector3(1783.89,2585.31,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		[127] = {position = vector3(1783.83,2581.6,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		[128] = {position = vector3(1783.94,2577.57,45.8), verticalOffsetX=-0.4, verticalOffsetY=0.1, verticalOffsetZ= 0.5, direction=34.23, bed=false, coords=true},
		--jail 1f sit other side
		[129] = {position = vector3(1775.22,2578.86,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},
		[130] = {position = vector3(1775.16,2582.95,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},
		[131] = {position = vector3(1775.24,2586.65,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},
		[132] = {position = vector3(1779.01,2586.64,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},
		[133] = {position = vector3(1782.68,2586.66,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},
		[134] = {position = vector3(1779.09,2582.95,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},
		[135] = {position = vector3(1782.65,2582.97,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},
		[136] = {position = vector3(1782.82,2578.98,45.8), verticalOffsetX=0.4, verticalOffsetY=-0.1, verticalOffsetZ= 0.5, direction=213.3, bed=false, coords=true},

	}
}

Config.Text = {
	SitOnChair = '按下 ~INPUT_ARREST~ 來 ~y~坐下',
	SitOnBed = '按下 ~INPUT_ARREST~ 來 ~y~坐在床上',
	LieOnBed = '按下 ~INPUT_ARREST~ 來 ~y~躺在床上',
	SwitchBetween = '~w~ 坐下、趴下、躺下 ~g~用箭頭[向右或向左]來切換',
	Standup = '按下 ~INPUT_CONTEXT~ 來 ~y~站起來'
}
